Refactoring out the get_worst_possible_profit method
liampauling/flumine pull request #399
Opened 2021-03-22 21:00 UTC by jsphon

I'd find the separate win/lose exposures useful when controlling risk in my strategy code.

2021-03-22 21:41 UTC, jsphon commented
Withdrawing for the time being, I think there might be some exposure problems that could be improved. I will investigate...

2021-03-22 22:39 UTC, jsphon commented
Reopenning this PR.
The changes allow a LAY bet to hedge a BACK bet, reducing exposure.
Please see `test_validate_selection2a` and `test_validate_selection2b` for examples.

2021-03-23 08:58 UTC, liampauling commented
With this being a breaking change to the return of a public method we would need to add some depreciation warnings first or add another method instead, thoughts?

2021-03-23 13:20 UTC, jsphon commented
I don't think this will change the result of the public method `selection_exposure`, and none of the tests for that method have broken/changed as a result.

This change could potentially affect users who don't want backs and lays to offset each other, from a risk perspective. If those users need to be a consideration, perhaps we could add a flag to `trading_controls.py`, to let users decide whether or not to use exposure offsetting.

2021-03-24 07:56 UTC, liampauling requested changes
Misread the git diff, few comments

2021-03-24 07:56 UTC, liampauling commented on flumine/markets/blotter.py
> +            "worst_potential_unmatched_profit_if_lose": unmatched_exposure[0],
Typo?

```
unmatched_exposure[0] -> unmatched_exposure[1]
```

2021-03-24 07:56 UTC, liampauling commented on flumine/markets/blotter.py
> +    def get_exposures(self, strategy, lookup: tuple) -> dict:
Move unit tests to this function

2021-03-24 07:56 UTC, liampauling commented on flumine/markets/blotter.py
> +        exposures = self.get_exposures(strategy=strategy, lookup=lookup)
Create new unit test for this function with get_exposures patched

2021-03-24 21:02 UTC, jsphon commented
Thanks for looking at this Liam. Following your comments, I have updated the code.

2021-03-25 05:57 UTC, liampauling approved these changes

2021-03-25 08:21 UTC, merged