Renaming hostname to customer_strategy_ref
liampauling/flumine pull request #488
Opened 2021-09-06 21:09 UTC by jsphon

Renaming `hostname` to `customer_strategy_ref`, which makes intent more explicit.

2021-09-07 08:33 UTC, liampauling requested changes

2021-09-07 08:33 UTC, liampauling commented on flumine/config.py
> +customer_strategy_ref = socket.gethostname()[
Can you add an alias below 

```python
hostname = customer_strategy_ref
```

We can then add a warning before removing it in the history as I know a few have used/changed this.

2021-09-08 01:27 UTC, ThomasAJ05 commented
I'm not sure this is an improvement as currently everywhere I see code like `self.customer_strategy_ref = config.hostname` I know more or less **exactly** what it means. Whereas with `self.customer_strategy_ref = config.customer_strategy_ref` I will (in the future when I have forgotten) I will have to go and check what initialized `config.customer_strategy_ref`.

Or to put it another way, the new code adds an unnecessary layer of possible obfuscation. Looking at '= config.hostname' vs '= config.customer_strategy_ref' I think the former is much clearer.

2021-09-08 07:54 UTC, jsphon commented
> I'm not sure this is an improvement as currently everywhere I see code like `self.customer_strategy_ref = config.hostname` I know more or less **exactly** what it means. Whereas with `self.customer_strategy_ref = config.customer_strategy_ref` I will (in the future when I have forgotten) I will have to go and check what initialized `config.customer_strategy_ref`.
> 
> Or to put it another way, the new code adds an unnecessary layer of possible obfuscation. Looking at `= config.hostname` vs `= config.customer_strategy_ref` I think the former is much clearer.

But config.hostname is just being used as the default value for customer_strategy_ref. If someone wants to use a different value, then it's a bit incorrect to call it config.hostname.

2021-09-08 08:05 UTC, ThomasAJ05 commented
Aha... "If someone wants to use a different value"... yes in that case you are correct.

2021-09-08 08:28 UTC, liampauling commented
@ThomasAJ05 that was my reasoning to start with but as @jsphon pointed out it is now only used for this variable so calling it hostname is a bit confusing (regular question on the slack)

2021-09-08 08:29 UTC, liampauling approved these changes

2021-09-08 08:43 UTC, merged